### PR TITLE
Copy ffmpeg to correct path after extract

### PR DESCRIPTION
**Pull request by zkrige**
Fixes: #916

### CODE REVIEW

**Comment by zkrige** [comment]
I haven't verified this on linux or windows, but from what I can see of the folder structure it should be ok

**Comment by zkrige** [comment]
that's odd. how did formatting pass for macOS and linux but not windows?
also prettier doesn't say what's wrong - it just gives a warning

**Comment by ayushmanchhabra** [comment]
That's been failing for other PRs too. Can we be ignored

**Comment by zkrige** [comment]
@ayushmanchhabra could you merge and do a build please. I need this for our CI

**Comment by ayushmanchhabra** [comment]
Could you update the changelog, bump to v4.3.7 and do an `npm install`? That way it would publish on merge.

**Review by ayushmanchhabra — APPROVED** [review]

**Pull request merged**
