### PR TITLE
feat(get): set `cacheDir` on another volume

### PR DESCRIPTION
**Pull request by jorisdugue**
### Description of Changes

- Use both absolute and relative paths for the cache directory.
-  Fixes the issue on MacOS related to the existence of a cache folder that is not present in the same current directory.
- Correctly unzips files in MacOs.

Notes: Resolves issued caused by cache is in a directory other than the current path.

Closes: #1017

### CODE REVIEW

**Comment by ayushmanchhabra** [comment]
I'm getting the same error in [GH-1017](https://github.com/nwutils/nw-builder/pull/1017). If you're able to resolve this error, that's be great. 🙏🏼

**Comment by ayushmanchhabra** [comment]
Weird that there's a lint error on Windows runner image only. Running `npm run lint:fix` and commiting the changes should fix it.

**Comment by ayushmanchhabra** [comment]
I'm good to merge this in but before I do, I have a few questions regarding implementation.

**Comment by jorisdugue** [comment]
What questions do you have? @ayushmanchhabra 

Additionally, it's worth mentioning that when working on Windows and wanting to create symbolic links, administrative privileges are necessary. Alternatively, you might consider using mlink, as it doesn't demand administrator rights.

**Comment by ayushmanchhabra** [comment]
> What questions do you have? @ayushmanchhabra
> 
> Additionally, it's worth mentioning that when working on Windows and wanting to create symbolic links, administrative privileges are necessary. Alternatively, you might consider using mlink, as it doesn't demand administrator rights.

@jorisdugue I've asked them above.

**Pull request merged**
